# coding: utf-8

"""
    Kapampangan Vocabulary MCP

    Vocabulary lookup service for the Kapampangan language tutor. Uses pgvector cosine similarity search against a PostgreSQL vocabulary table populated from canonical data files.  Called by the orchestration layer's agentic tool loop. Can also be queried directly here for manual testing. 

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from mcp_vocabulary_api.apis.admin_api import router as AdminApiRouter
from mcp_vocabulary_api.apis.lookup_api import router as LookupApiRouter
from mcp_vocabulary_api.apis.status_api import router as StatusApiRouter
from mcp_vocabulary_api.apis.vocabulary_api import router as VocabularyApiRouter

app = FastAPI(
    title="Kapampangan Vocabulary MCP",
    description="Vocabulary lookup service for the Kapampangan language tutor. Uses pgvector cosine similarity search against a PostgreSQL vocabulary table populated from canonical data files.  Called by the orchestration layer&#39;s agentic tool loop. Can also be queried directly here for manual testing. ",
    version="0.2.0",
)

app.include_router(AdminApiRouter)
app.include_router(LookupApiRouter)
app.include_router(StatusApiRouter)
app.include_router(VocabularyApiRouter)
