FROM python:3.12-slim
WORKDIR /app
COPY libs/ /libs/
COPY app/requirements.txt .
RUN pip install --no-cache-dir /libs/kapampangan_obs -r requirements.txt && \
    rm -rf /libs/
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
