from pydantic import BaseModel, Field
from typing import Optional


class Message(BaseModel):
    role: str = Field(..., description='"user" or "assistant"', examples=["user"])
    content: str = Field(..., examples=["How do I say 'I'm hungry' in Kapampangan?"])


class ChatRequest(BaseModel):
    messages: list[Message]
    session_id: str = Field(default="", description="Opaque session identifier; generated by the client and echoed back in traces")

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "session_id": "demo-session-1",
                    "messages": [
                        {"role": "user", "content": "How do I say 'I'm hungry' in Kapampangan?"}
                    ],
                },
                {
                    "session_id": "demo-session-2",
                    "messages": [
                        {"role": "user", "content": "Explain the progressive aspect of mangan"},
                    ],
                },
            ]
        }
    }


class ToolCall(BaseModel):
    name: str
    parameters: dict


class ToolResult(BaseModel):
    tool_name: str
    result: dict
    error: Optional[str] = None
